Fixing resource name
Boxen throws the following error:

    Error: Execution of '/usr/sbin/chown -R <user>:<group>
    /Applications/Fluid-1.7.2.app' returned 1: chown:
    /Applications/Fluid-1.7.2.app: No such file or directory

The app is really called Fluid.app.